runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  DATABASE_URL: 'postgresql://[USERNAME]:[PASSWORD]@/[DATABASE_NAME]?host=/cloudsql/[INSTANCE_CONNECTION_NAME]'
  SESSION_SECRET: '[YOUR_SESSION_SECRET]'
  
  # OAuth credentials
  GOOGLE_CLIENT_ID: '[YOUR_GOOGLE_CLIENT_ID]'
  GOOGLE_CLIENT_SECRET: '[YOUR_GOOGLE_CLIENT_SECRET]'
  GOOGLE_CALLBACK_URL: 'https://[YOUR_PROJECT_ID].uc.r.appspot.com/api/auth/google/callback'
  
  FACEBOOK_APP_ID: '[YOUR_FACEBOOK_APP_ID]'
  FACEBOOK_APP_SECRET: '[YOUR_FACEBOOK_APP_SECRET]'
  FACEBOOK_CALLBACK_URL: 'https://[YOUR_PROJECT_ID].uc.r.appspot.com/api/auth/facebook/callback'
  
  APPLE_CLIENT_ID: '[YOUR_APPLE_CLIENT_ID]'
  APPLE_TEAM_ID: '[YOUR_APPLE_TEAM_ID]'
  APPLE_KEY_ID: '[YOUR_APPLE_KEY_ID]'
  APPLE_CALLBACK_URL: 'https://[YOUR_PROJECT_ID].uc.r.appspot.com/api/auth/apple/callback'
  
  # App URL
  APP_URL: 'https://[YOUR_PROJECT_ID].uc.r.appspot.com'

beta_settings:
  cloud_sql_instances: '[YOUR_INSTANCE_CONNECTION_NAME]'

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto