steps:
# Install dependencies
- name: 'node:20'
  entrypoint: npm
  args: ['ci']

# Run database migrations
- name: 'node:20'
  entrypoint: node
  args: ['--experimental-modules', 'predeploy.js']
  env:
  - 'DATABASE_URL=${_DATABASE_URL}'
  - 'NODE_ENV=production'

# Build the app
- name: 'node:20'
  entrypoint: npm
  args: ['run', 'build']

# Deploy to App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --quiet']

substitutions:
  _DATABASE_URL: 'postgresql://[USERNAME]:[PASSWORD]@[HOST]:[PORT]/[DATABASE_NAME]?sslmode=require'

options:
  logging: CLOUD_LOGGING_ONLY